/**
 * Copyright (C) 2022 Duck McSouls
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { bool } from "/lib/constant/bool.js";
import { log } from "/lib/io.js";
import { buy_all_programs } from "/lib/singularity/program.js";
import { has_gang_api } from "/lib/source.js";

/**
 * Purchase programs via the dark web.  We use any money available to us, most
 * likely money generated by our gang.
 *
 * Usage: run gang/program.js
 *
 * @param ns The Netscript API.
 */
export async function main(ns) {
    // Less verbose log.
    ns.disableLog("getServerMoneyAvailable");
    ns.disableLog("sleep");
    // Purchase programs via the dark web.
    if (has_gang_api(ns)) {
        log(ns, "Buy programs via dark web");
        await buy_all_programs(ns, bool.NO_VISIT, bool.NO_WORK);
    }
}
